name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

  workflow_dispatch:

env:
  TERRAFORM_WORKING_DIRECTORY: "terraform"
  ECR_REPOSITORY: "my-lambda-image"
  ENVIRONMENT_NAME: "dev"
  AWS_REGION: 'eu-central-1'
  TF_VERSION: '1.6.0'
  IMAGE_TAG: latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4
    
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: false

    - id: apply
      name: Terraform Apply
      working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
      run: |
        terraform init -backend-config="bucket=${{ env.TF_S3_BUCKET_BACKEND_NAME }}" \
            -backend-config="region=${{ env.AWS_REGION }}"

        terraform apply -auto-approve -var="lambda_image_uri=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"

