name: terraform-destroy

on:
  workflow_dispatch:  # temporaly Manual trigger only

env:
  TERRAFORM_WORKING_DIRECTORY: "terraform"
  ECR_REPOSITORY: "my-lambda-image"
  ENVIRONMENT_NAME: "dev"
  AWS_REGION: 'eu-central-1'
  TF_VERSION: '1.6.0'
  IMAGE_TAG: latest

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: false

    - id: destroy
      name: Terraform Destroy
      working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
      run: |
        terraform init \
          -backend-config="bucket=${{ vars.TF_S3_BUCKET_BACKEND_NAME }}" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="key=terraform/dev.tfstate"

        terraform destroy -auto-approve \
          -var="lambda_image_uri=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
